services:
  - type: web
    name: audiototext-api
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /docs
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ASSEMBLYAI_API_KEY
        sync: false
