services:
  - type: web
    name: audiototext-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASSEMBLYAI_API_KEY
        value: c050c9bad17d4de885b6e8a23d2445ff
